# Generated by Django 5.2.4 on 2025-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Customer', 'customer'), ('Vendor', 'vendor')], max_length=10)),
                ('phone', models.IntegerField(max_length=15)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
